import os
import argparse
import anthropic
from google.cloud import bigquery

def main():
    """
    Argparse wrapper for command-line usage.

    Args:
        None.

    Returns:
        None.
    """
    parser = argparse.ArgumentParser(
        description="Query BigQuery for 2023-2024 NHL hockey stats using natural language."
    )
    parser.add_argument(
        "question",
        type=str,
        help="Your question for 2023-2024 NHL stats e.g. 'Who has the most points?'"
    )

    args = parser.parse_args()
    hockey_rag(args.question)


def generate_sql(question: str) -> str:
    """
    Use Claude to convert a natural language question into a BigQuery SQL query.

    Args:
        question - User's natural language query.

    Returns:
        BigQuery SQL query string.
    """
    project_id = os.environ.get('GOOGLE_CLOUD_PROJECT')
    client = anthropic.Anthropic()

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": f"""You are a BigQuery SQL generator for NHL hockey stats.

The table is `{project_id}.hockey_dbt_dev.mart_skater_stats` and contains these fields:
- player_name (STRING) — full name e.g. "Connor McDavid"
- team (STRING) — 3 letter abbreviation e.g. "EDM", "TOR", "BOS"
- position (STRING) — "C", "L", "R", "D"
- games_played (INTEGER)
- goals (INTEGER)
- assists (INTEGER)
- points (INTEGER)
- plus_minus (INTEGER)
- penalty_minutes (INTEGER)
- power_play_goals (INTEGER)
- power_play_points (INTEGER)
- short_handed_goals (INTEGER)
- shots (INTEGER)
- shooting_pct (FLOAT) — e.g. 0.152 means 15.2%
- toi_per_game (FLOAT) — time on ice in seconds per game
- goals_per_game (FLOAT)
- assists_per_game (FLOAT)
- points_per_game (FLOAT)
- shots_per_game (FLOAT)

Convert this question into a valid BigQuery SQL query.
Return ONLY the raw SQL string, no explanation, no markdown, no backticks.

Question: {question}"""
            }
        ]
    )

    return message.content[0].text.strip()


def query_bigquery(sql: str) -> list[dict]:
    """
    Executes a SQL query against BigQuery and returns results as a list of dicts.

    Args:
        sql - BigQuery SQL query string.

    Returns:
        List of rows as dicts.
    """
    client = bigquery.Client()

    # safety check -- only allow SELECT statements
    if not sql.strip().upper().startswith('SELECT'):
        raise ValueError("Only SELECT queries are permitted.")

    results = client.query(sql).result()
    return [dict(row) for row in results]


def claude_summary(question: str, context: list[dict]) -> str:
    """
    Summarizes BigQuery results using Claude.

    Args:
        question - Original natural language question.
        context - BigQuery query results as list of dicts.

    Returns:
        Natural language summary of results generated by Claude.
    """
    client = anthropic.Anthropic()

    context_str = "\n".join([
        f"{p.get('player_name')} ({p.get('position')}, {p.get('team')}): "
        f"{p.get('games_played')} GP, {p.get('goals')} G, {p.get('assists')} A, "
        f"{p.get('points')} PTS, {p.get('points_per_game')} P/GP, "
        f"{p.get('shooting_pct', 0):.3f} SH%, "
        f"{p.get('plus_minus')} +/-, "
        f"{p.get('power_play_goals')} PPG, {p.get('power_play_points')} PPP"
        for p in context
    ])

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": f"""You are a hockey analytics assistant.
Use the following player data to answer the question.

Player Data:
{context_str}

Question: {question}

Answer based only on the data provided."""
            }
        ]
    )

    return message.content[0].text


def hockey_rag(question: str):
    """
    Answers natural language questions about 2023-2024 hockey stats using BigQuery and Claude.

    Args:
        question - User query.

    Returns:
        Natural language answer generated by Claude based on BigQuery results.
    """
    print(f"\nQuestion: {question}")
    print("Generating SQL query...")

    sql = generate_sql(question)
    print(f"\nGenerated SQL:\n{sql}\n")

    print("Querying BigQuery...")
    try:
        results = query_bigquery(sql)
    except Exception as e:
        print(f"Query failed: {e}")
        return

    if not results:
        print("No results found.")
        return

    print(f"Found {len(results)} results, generating answer...")
    answer = claude_summary(question, results)
    print(f"\nAnswer: {answer}")


if __name__ == '__main__':
    main()