import json
import os
import argparse
import anthropic
from elasticsearch import Elasticsearch

def main():
    """
    Argparse wrapper for command-line usage.

    Args:
        None.

    Returns:
        None.
    
    """

    parser = argparse.ArgumentParser(
        description="Query Elasticsearch for 2023-2024 NHL hockey stats using natural language."
    )
    parser.add_argument(
        "question",
        type=str,
        help="Your question for 2023-2024 NHL stats e.g. 'Who has the most points?'"
    )

    args = parser.parse_args()
    hockey_rag(args.question)

def generate_es_query(question: str) -> dict:
    """
    Use Claude to convert a natural language question into an Elasticsearch-formatted query.

    Args:
        question - User's natural language query.

    Returns:
        Elasticsearch-formatted query of the user's input.
    
    """
    client = anthropic.Anthropic()
    
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": f"""You are an Elasticsearch query generator for NHL hockey stats.

The index contains these fields:
- player_name (text) — full name e.g. "Connor McDavid"
- team (keyword) — 3 letter abbreviation e.g. "EDM", "TOR", "BOS"
- position (keyword) — "C", "L", "R", "D"
- games_played (integer)
- goals (integer)
- assists (integer)
- points (integer)
- plus_minus (integer)
- penalty_minutes (integer)
- power_play_goals (integer)
- power_play_points (integer)
- short_handed_goals (integer)
- shots (integer)
- shooting_pct (float) — e.g. 0.152 means 15.2%
- toi_per_game (float) — time on ice in seconds per game
- goals_per_game (float)
- assists_per_game (float)
- points_per_game (float)
- shots_per_game (float)

Convert this question into a valid Elasticsearch query JSON object.
Return ONLY the raw JSON query object, no explanation, no markdown, no backticks.

Question: {question}"""
            }
        ]
    )
    
    raw = message.content[0].text.strip()
    return json.loads(raw)


def search_elasticsearch(question: str) -> list[dict]:
    """
    Searches Elasticsearch with a Claude-generated Elasticsearch query.

    Args:
        question - Claude-generated Elasticsearch-formatted query.

    Returns:
        List of top 10 relevant hits from Elasticsearch.
    
    """
    host = 'http://localhost:9200' #Different than container because this script is meant to be run locally, not on Docker
    es = Elasticsearch(host)
    index = 'skater_stats'
    size = 10
    
    es_query = generate_es_query(question)
    
    response = es.search(index=index, body={**es_query, "size": size})
    return [hit["_source"] for hit in response["hits"]["hits"]]


def claude_summary(question: str, context: list[dict]) -> str:
    """
    Summarizes Elasticsearch results using Claude.

    Args:
        question - Claude-generated Elasticsearch-formatted query.
        context - Elasticsearch results

    Returns:
        Natural language-generated summary of Elasticsearch query results, generated by Claude.
    
    """
    client = anthropic.Anthropic()
    
    context_str = "\n".join([
        f"{p.get('player_name')} ({p.get('position')}, {p.get('team')}): "
        f"{p.get('games_played')} GP, {p.get('goals')} G, {p.get('assists')} A, "
        f"{p.get('points')} PTS, {p.get('points_per_game')} P/GP, "
        f"{p.get('shooting_pct', 0):.3f} SH%, "
        f"{p.get('plus_minus')} +/-, "
        f"{p.get('power_play_goals')} PPG, {p.get('power_play_points')} PPP"
        for p in context
    ])
    
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": f"""You are a hockey analytics assistant.
Use the following player data to answer the question.

Player Data:
{context_str}

Question: {question}

Answer based only on the data provided."""
            }
        ]
    )
    
    return message.content[0].text


def hockey_rag(question: str):
    """
    Ingests and answers natural language questions about 2023-2024 hockey stats store in Elasticsearch.

    Args:
        question - User query.

    Returns:
        Natural language-generated summary of Elasticsearch query results, generated by Claude.
    
    """
    print(f"\nQuestion: {question}")
    print("Searching player data...")
    
    context = search_elasticsearch(question)
    
    if not context:
        print("No relevant players found")
        return
    
    print(f"Found {len(context)} relevant players, asking Claude...")
    answer = claude_summary(question, context)
    print(f"\nAnswer: {answer}")

if __name__ == '__main__':
    main()