version: 2

models:
  - name: mart_skater_stats
    columns:
      - name: player_id
        data_tests:
          - not_null
          - unique
      - name: points_per_game
        data_tests:
          - not_null

  - name: mart_goalie_stats
    columns:
      - name: player_name
        data_tests:
          - not_null
      - name: save_pct
        data_tests:
          - not_null

  - name: mart_team_standings
    columns:
      - name: team_name
        data_tests:
          - not_null
          - unique